### ISSUE TITLE
2024.12.0 beta issue for timezonefinder

### ISSUE THREAD

**Issue by Mariusthvdb** [pnbruckner/ha-entity-tz#17]
integration wont startup:
```
Logger: homeassistant.setup
Bron: setup.py:269
Eerst voorgekomen: 23:15:54 (1 gebeurtenissen)
Laatst gelogd: 23:15:54

Setup failed for custom integration 'entity_tz': Requirements for entity_tz not found: ['timezonefinder==6.5.3'].
```

```
Logger: homeassistant.util.package
Bron: util/package.py:152
Eerst voorgekomen: 23:15:27 (3 gebeurtenissen)
Laatst gelogd: 23:15:54

Unable to install package timezonefinder==6.5.3: × Failed to download and build `h3==3.7.7` ╰─▶ Build backend failed to build wheel through `build_wheel` (exit status: 1) [stderr] Traceback (most recent call last): File "/tmp/.tmpNrt05n/builds-v0/.tmpFRO9VX/lib/python3.13/site-packages/skbuild/setuptools_wrap.py", line 639, in setup cmkr = cmaker.CMaker(cmake_executable) File "/tmp/.tmpNrt05n/builds-v0/.tmpFRO9VX/lib/python3.13/site-packages/skbuild/cmaker.py", line 145, in __init__ self.cmake_version = get_cmake_version(self.cmake_executable) ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/.tmpNrt05n/builds-v0/.tmpFRO9VX/lib/python3.13/site-packages/skbuild/cmaker.py", line 102, in get_cmake_version raise SKBuildError(msg) from err Problem with the CMake installation, aborting build. CMake executable is /tmp/.tmpNrt05n/builds-v0/.tmpFRO9VX/lib/python3.13/site-packages/cmake/data/bin/cmake help: `h3` (v3.7.7) was included because `timezonefinder` (v6.5.3) depends on `h3`
Unable to install package timezonefinder==6.5.3: × Failed to download and build `h3==3.7.7` ╰─▶ Build backend failed to build wheel through `build_wheel` (exit status: 1) [stderr] Traceback (most recent call last): File "/tmp/.tmpbNf7pM/builds-v0/.tmpi8ijvv/lib/python3.13/site-packages/skbuild/setuptools_wrap.py", line 639, in setup cmkr = cmaker.CMaker(cmake_executable) File "/tmp/.tmpbNf7pM/builds-v0/.tmpi8ijvv/lib/python3.13/site-packages/skbuild/cmaker.py", line 145, in __init__ self.cmake_version = get_cmake_version(self.cmake_executable) ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/.tmpbNf7pM/builds-v0/.tmpi8ijvv/lib/python3.13/site-packages/skbuild/cmaker.py", line 102, in get_cmake_version raise SKBuildError(msg) from err Problem with the CMake installation, aborting build. CMake executable is /tmp/.tmpbNf7pM/builds-v0/.tmpi8ijvv/lib/python3.13/site-packages/cmake/data/bin/cmake help: `h3` (v3.7.7) was included because `timezonefinder` (v6.5.3) depends on `h3`
Unable to install package timezonefinder==6.5.3: × Failed to download and build `h3==3.7.7` ╰─▶ Build backend failed to build wheel through `build_wheel` (exit status: 1) [stderr] Traceback (most recent call last): File "/tmp/.tmpoABizA/builds-v0/.tmpm9QRMF/lib/python3.13/site-packages/skbuild/setuptools_wrap.py", line 639, in setup cmkr = cmaker.CMaker(cmake_executable) File "/tmp/.tmpoABizA/builds-v0/.tmpm9QRMF/lib/python3.13/site-packages/skbuild/cmaker.py", line 145, in __init__ self.cmake_version = get_cmake_version(self.cmake_executable) ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^ File "/tmp/.tmpoABizA/builds-v0/.tmpm9QRMF/lib/python3.13/site-packages/skbuild/cmaker.py", line 102, in get_cmake_version raise SKBuildError(msg) from err Problem with the CMake installation, aborting build. CMake executable is /tmp/.tmpoABizA/builds-v0/.tmpm9QRMF/lib/python3.13/site-packages/cmake/data/bin/cmake help: `h3` (v3.7.7) was included because `timezonefinder` (v6.5.3) depends on `h3`
```

**Comment by Mariusthvdb** [comment]
edited the manifest to use version 6.5.5
`  "requirements": ["async-lru==2.0.4", "timezonefinder==6.5.5"],`

but still on 2024.11.3 now so cant test if that helps
it seems to have several relevant updates listed https://github.com/jannikmi/timezonefinder/releases so will let you know if this fixes it (after the dev team has fixed several other broken core integrations) when back on beta 2024.12

**Comment by Mariusthvdb** [comment]
running fine with the above change in the manifest in 2024.12.0.b3

**Comment by pnbruckner** [comment]
Thanks. I'm working on updating all of my custom integrations to drop support for HA versions older than 2024.8.3. I'll update to the latest version of timezonefinder before releasing.
